package model.report;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import lombok.Builder;
import lombok.Data;

/**
 * Complete matchup analysis report containing user statistics, peak player performances, and close
 * matchup information.
 *
 * <p>Generated by CalcMatchups and serialized to JSON for analysis.
 */
@Data
@Builder
public class MatchupReport {
  private LocalDateTime generatedAt;
  private int totalMatchups;
  private List<UserMatchupStats> userMatchupStats;
  private PeakPlayerStats peakPlayerStats;
  private ClosestMatchupInfo closestLoss;
  private Map<String, Integer> closeLossCounts; // userName -> count of losses by threshold

  /**
   * Peak performance statistics for individual players across all matchups.
   *
   * <p>Tracks highest weekly point totals and most donuts (0-point performances) by player.
   */
  @Data
  @Builder
  public static class PeakPlayerStats {
    private Map<String, Integer> mostDonutPlayers; // playerName -> donut count
    private Map<String, Double> highestWeeklyPtsPlayers; // playerName -> max pts
    private Map<String, Double> mostQbPtsPlayers;
    private Map<String, Double> mostWrPtsPlayers;
    private Map<String, Double> mostTePtsPlayers;
    private Map<String, Double> mostRbPtsPlayers;
  }

  /**
   * Information about the closest matchup loss in the season.
   *
   * <p>Identifies which user had the closest loss and by how many points.
   */
  @Data
  @Builder
  public static class ClosestMatchupInfo {
    private String userName;
    private double pointDifference;
  }
}
